<a href="https://colab.research.google.com/github/JiaHua-Chang/-/blob/main/0331.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
A=5
B=6
X=A+B
print("a,b相加的值為{}".format(X))

AA=3
BB=5
XX=AA+BB
print(XX)


a,b相加的值為11
8


In [ ]:

a=10
b=29
c=9
sum=a+b+c
avg=sum/3
print("總分:{} \n平均:{}".format(sum,avg))

總分:48 
平均:16.0


In [ ]:
a=int(input("請輸入數值"))
b=int(input("請輸入數值"))
print(a+b)

請輸入數值6
請輸入數值38
44


In [ ]:
a=int(input("請輸入數值"))
if (a>90):
  print("吃飯")
else:
  print("打咚咚")

請輸入數值92
吃飯


In [ ]:
##  分數等級

a=int(input("請輸入數值"))
if (a>=90):
  print("A")
if (a>=80 and a<90):
  print("B")
if (a>=70 and a<80):
  print("C")
if (a>=60 and a<70):
  print("D")
if (a<60):
  print("不及格")

請輸入數值75
C


In [ ]:
a=int(input("請輸入數值"))
b=int(input("請輸入數值"))
if(a>b):
  print(a)
else:
  print(b)

請輸入數值20
請輸入數值39
39


In [ ]:
a=int(input("請輸入數值"))
b=int(input("請輸入數值"))
c=int(input("請輸入數值"))
if(a>b and a>c):
  print(a)
if(b>a and b>c):
  print(b)
if(c>a and c>b):
  print(c)

In [ ]:
sum=0
for i in range(1,101,2):
  sum=sum+i
print("總和為{}".format(sum))

總和為2500


In [ ]:
sum=0
for i in range(1,31,2):
  sum=sum+i
print("總和為{}".format(sum))

總和為225


In [ ]:
a=0
print(type(a))

<class 'int'>


In [ ]:
password=123
for i in range(1,4,1):
  inp=int(input("請輸入密碼: "))
  if inp==password:
   print("密碼正確,進入系統")
   break
  else:
   print("密碼錯誤")




請輸入密碼: 123
密碼正確,進入系統


In [ ]:

import random ##直到答對才跳出迴圈
bigsmall=random.randint(1,100)
i=0
while True:
  i=i+1
    ##for i in range(1,10,1):
  inp=int(input("請輸入值比大小: "))
  if inp==bigsmall:
   print("你對了啦,(第{}次".format(i))
   break
  elif inp>bigsmall:
   print("你猜太大了啦,第{}次".format(i))
  elif inp<bigsmall:
   print("你猜太小了啦,第{}次".format(i))


In [ ]:
import random
bigsmall=random.randint(1,100)
i=0
while True:
  i=i+1
    ##for i in range(1,10,1):
  inp=int(input("請輸入值比大小: "))
  if inp==bigsmall:
   print("你對了啦,第{}次".format(i))
   break
  elif inp>bigsmall:
   print("你猜太大了啦,第{}次".format(i))
  elif inp<bigsmall:
   print("你猜太小了啦,第{}次".format(i))

In [ ]:
##list的應用
m=[12,23,34,45,65]
for i in range(0,5,1):
 print("第{}值為:{}".format(i+1,m[i]))

In [ ]:
##list的應用加總
m=[12,23,34,45,65]
sum=0
for i in range(0,5,1):
  sum=sum+m[i]
print("加總:{}".format(sum))

In [ ]:
##使用者輸入五個數值,加總並秀出,使用陣列
a=int(input("請輸入數值1:"))
b=int(input("請輸入數值2:"))
c=int(input("請輸入數值3:"))
d=int(input("請輸入數值4:"))
e=int(input("請輸入數值5:"))
m=[a,b,c,d,e]
sum=0
for i in range(0,5,1):
  sum=sum+m[i]
print("加總:{}".format(sum))

In [ ]:
##使用者輸入五個數值,加總並秀出
list=[]
sum=0
for i in range(0,5,1):
  a=int(input("請輸入數值"))
  list.append(a);##依序填入list
  sum=sum+a
print(sum)

In [ ]:
a=['java',"ggggg","hhhhh","eyyeyye","wwwww"]
a=['java',"ggggg","hhhhh","eyyeyye","wwwww"]
print(a[0])
print(a[0:2])
print(a[0])
print(a[0:2])

In [ ]:
list=[]  ##直接給一個空的陣列填入值
sum=0
for i in range(6):
  a=int(input("輸入數值:"))
  list.append(a)  ##依序填入List
  sum=sum+a
print(sum)

In [ ]:
dict={'a':1,'b':5,'b':77}
print(dict['b'])

In [ ]:
dict={'NAME':'JACK','AGE':100,'SCHOOL':'你好'}
dict['AGE']=20
dict['big']='雞蛋'
print("dict['AGE']:",dict['AGE'])
print(dict)
print(dict.keys())
print(dict.values())
print(len(dict))

In [ ]:
a=input("請輸入字串:")
print(list(a))
print(a)
print([a])
print(a.spilt())

In [ ]:
##使用套件建立陣列

import numpy as nb
a=nb.array([12,23,44])  ##一維
b=nb.array([[233.3,345.6,566.7,463.5],[111.4,374.7,157.5,666.7]],dtype = float) ##二維資料型態
print(a)
print(b)
print(b.ndim)  ##幾維
print(b.shape) ##兩個框框內有4個元素 要成對前後框框需要一樣的數量 兩列四個欄位
print(b.size)  ##元素
print(len(b))  ##幾個中框框
nb.arange(1, 30, 2)
##print(nb.arange)

In [ ]:
##系統存檔
import numpy as nb
origial_array=nb.array([16,92,53])
nb.save("my_array2",origial_array) ##原始文件
nb.savetxt("my_array2.txt",origial_array)##存成txt文件
array_from_npy=nb.load("my_array2.npy")##讀取原始文件
print(array_from_npy)
array_from_txtfile=nb.loadtxt("my_array2.txt")##讀取txt文件
print(array_from_txtfile)

[16 92 53]
[16. 92. 53.]


In [ ]:
import numpy as nb
a=nb.arange(15).reshape(3,5)##0到14分為三列五個欄位
a[2]=14
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [14 14 14 14 14]]


In [ ]:
import pandas as pd
s=pd.Series({"NAME":"JACK","AGE":28,"愛吃的東西":"雞蛋"})
# s["你好"]=19
s["愛吃的東西"]='鴨蛋'
print(s)

In [ ]:
import numpy as nb
a=nb.arange(1,10,2)
a[1]=8
print(a)

[1 8 5 7 9]


In [ ]:
import pandas as pd
a=pd.Series([34,12,46,57,54])
print(a)
a1=pd.Series([34,12,46,57,54], index=['小名','曉華','小賴','你好','老師好'])
print(a1[1:4])
print(a1[1:3]) ##呼叫從1~2的值
print(a1['你好']) ##呼叫你好的分數


In [ ]:
import pandas as pd
cc={'name':['小名','曉華','小賴','你好','老師'],'math':[12,34,56,24,75],'eng':[45,76,88,90,47],'chi':[56,67,70,85,90]} ##字典
cc1=pd.DataFrame(cc)##字典轉換,大小寫要注意
print(cc1)
cc2=pd.DataFrame(cc,index=['one','two','three','four','five']) ##修改列的名稱
print(cc2)
cc['小名']=23
print(cc2[0:3]) ##不能單獨呼叫名字,只能呼叫name,math
print("222",cc1.info())
print("印出索引",cc2.index)
print("印出欄",cc2.columns)
print(cc2.head(2)) ##從頭開始數
print(cc2.tail(2)) ##從尾開始數

  name  math  eng  chi
0   小名    12   45   56
1   曉華    34   76   67
2   小賴    56   88   70
3   你好    24   90   85
4   老師    75   47   90
      name  math  eng  chi
one     小名    12   45   56
two     曉華    34   76   67
three   小賴    56   88   70
four    你好    24   90   85
five    老師    75   47   90
      name  math  eng  chi
one     小名    12   45   56
two     曉華    34   76   67
three   小賴    56   88   70
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    5 non-null      object
 1   math    5 non-null      int64 
 2   eng     5 non-null      int64 
 3   chi     5 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 288.0+ bytes
222 None
印出索引 Index(['one', 'two', 'three', 'four', 'five'], dtype='object')
印出欄 Index(['name', 'math', 'eng', 'chi'], dtype='object')
    name  math  eng  chi
one   小名    12   45   56
two   曉華    34   76   67
     name  

In [ ]:
import pandas as pd
a=pd.read_excel('/content/test.xlsx')
print(a)

In [ ]:
import pandas as pd ##series數字
data=pd.Series([6,7,-2,8,9],index=["a","b","c","d","e"])

print(data.dtype)
print(data.max())
print(data.min())
print(data.sum())
print(data.prod())
print(data.mean())
print(data[2])
print(data["e"])
print(data.index)
print(data.iloc[1])

int64
9
-2
28
-6048
5.6
-2
9
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
7


<ipython-input-7-4c66b7869917>:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(data[2])


In [ ]:
import pandas as pd ##series字串
data=pd.Series(["你好","HELLO","PYTHON"])
print(data.str.lower())##小寫
print(data.str.len())##長度
print(data.str.cat(sep='--'))##串接
print(data.str.contains("HELLO"))##搜尋
print(data.str.replace("你好","媽媽"))###取代


0        你好
1     hello
2    python
dtype: object
0    2
1    5
2    6
dtype: int64
你好--HELLO--PYTHON
0    False
1     True
2    False
dtype: bool
0        媽媽
1     HELLO
2    PYTHON
dtype: object


In [ ]:
##網路爬蟲螢幕截圖
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
!pip install selenium



Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2,517 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,226 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/restrict

In [ ]:
from selenium import webdriver
from selenium import webdriver.options
options=options()
options.chrome.executable_path="/content/chromedriver.exe"
drive=webdriver.chrome(options=options)
drive.get("https:google.com/")
drive.save("goole.png")
drive.close()